/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connect_card;

import java.util.List;
import javax.smartcardio.*;
import javax.swing.JOptionPane;
/**
 *
 * @author daotu
 */
public class view extends javax.swing.JFrame {
    public static final byte [] AID_APPLET = { (byte)0x11,(byte)0x22, (byte)0x33,(byte)0x44, (byte)0x55,(byte)0x00 };
    private Card card;
    private TerminalFactory factory;
    private CardChannel channel;
    private CardTerminal terminal;
    private List<CardTerminal> terminals;
    private ResponseAPDU response;
    public String textReponsString;
    public boolean connectCard(){
            try {
            factory= TerminalFactory.getDefault();
            terminals=  factory.terminals().list();
            terminal= terminals.get(0);
            card =terminal.connect("T=0");
            channel= card.getBasicChannel();
                if (channel== null) {
                    return false;
                    
                }
            response= channel.transmit(new CommandAPDU(0x01, (byte) 0xA4, 0x04, 0x00, AID_APPLET));
             textReponsString = Integer.toHexString(response.getSW());
            
                System.out.println(textReponsString);
                if (textReponsString.equals("9000")) {
                    return true;
                    
                }else if (textReponsString.equals("6400")) {
                    JOptionPane.showMessageDialog(null, "Thẻ đã bị vô hiệu hóa");
                    return true; 
                }else   {
                     return false;
                     
                }
            
            
                
                
            } catch (Exception e) {
            }
            textReponsString="";
            return false;
    }
            
    public boolean disconnect(){
        try {
            card.disconnect(false);
            return true;
        } catch (Exception e) {
            System.out.println("lỗi : "+ e);
        }
        return false;
        
    }
    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSend = new javax.swing.JButton();
        tvKQ = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSend.setText("Gửi");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        tvKQ.setText("Kêt quả");
        tvKQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvKQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnSend))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(tvKQ, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnSend)
                .addGap(27, 27, 27)
                .addComponent(tvKQ, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        
        if (connectCard()) {
            tvKQ.setText(Integer.toHexString(response.getSW()););
        }else{
            tvKQ.setText("k thành công");
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void tvKQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvKQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvKQActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JTextField tvKQ;
    // End of variables declaration//GEN-END:variables
}
